### PR TITLE
Remove database service checks and pg gem

### PR DESCRIPTION
**Pull request by carbonin**
We need to keep the database packages because we still install
PG as a dependency of api-common

### CODE REVIEW

**Comment by agrare** [comment]
Getting the following error when running with this:
```
[----] I, [2019-03-06T14:01:11.262941 #10387:2b0b764c4e54]  INFO -- : Started POST "/topological_inventory/ingress_api/0.0.2/inventory" for 127.0.0.1 at 2019-03-06 14:01:11 -0500
[----] F, [2019-03-06T14:01:11.268015 #10387:2b0b764c4e54] FATAL -- :   
[----] F, [2019-03-06T14:01:11.268231 #10387:2b0b764c4e54] FATAL -- : ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found.):
[----] F, [2019-03-06T14:01:11.268393 #10387:2b0b764c4e54] FATAL -- :   
[----] F, [2019-03-06T14:01:11.268730 #10387:2b0b764c4e54] FATAL -- : activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1009:in `retrieve_connection'
```

**Comment by carbonin** [comment]
Really? I'm running it in openshift with no problems ...

**Comment by carbonin** [comment]
I'm also not sure how that's possible. This should be a noop for running locally, all I did was remove a gem that gets brought in anyway by api common. :worried:

**Comment by agrare** [comment]
Oh I thought you were trying to get it to run without a database url, so manageiq-api-common still pulls in the pg gem and this still needs access to a DB for now right?

**Comment by carbonin** [comment]
Oh damn, I didn't push the change to the deployment let me try that out.

**Comment by carbonin** [comment]
@agrare looks like we need to pass a dummy `DATABASE_URL` to make active record happy. I added it to the Dockerfile.

**Pull request merged**
