### PR TITLE
Generated ingress api open api json

### PR DESCRIPTION
**Pull request by Ladas**
Creating openapi.json using a generator. Generating specific InventoryObject and InventoryObjectLazy, so we can validate them.

### CODE REVIEW

**Comment by Ladas** [comment]
@abellotti please review, this is a openapi.json from a new generator in https://github.com/ManageIQ/topological_inventory-persister/pull/31. it should allow us to do a very strict validation of the request body

**Comment by abellotti** [comment]
This looks good, just minor things that the editor complained about.
- InventoryCollection, InventoryObjectLazy, Source schema definition is not being used.
- some properties declared via a $ref have additional attributes (nullable), not sure if that's being honored. maybe put as part of the $ref'd definition.

Nice usage of oneOf and discriminators :)

**Comment by Ladas** [comment]
@abellotti right, we use the generic InventoryCollection, InventoryObjectLazy in the collectors. So we'll have to rewrite the collector helpers before we can remove them. I think I can remove the Source, good catch.

Can you elaborate more on the second point? Some example? I am not sure what you mean.

**Comment by abellotti** [comment]
When I was viewing the spec via the openapi editor, I saw complaints as follows:

```
            container_image:
                 $ref: '#/components/schemas/ContainerImageReference'
                 nullable: true
```

With error on the nullable: true line saying **Sibling values are not allowed alongside $refs**

Not sure if the client will just be ignoring that nullable. The OpenAPI spec is probably expecting the nullable: true to be part of the _#/components/schemas/ContainerImageReference_ definition, but I could be wrong.

**Comment by Ladas** [comment]
@abellotti ah good catch, yeah looks like those will be ignored. I can't move it inside of the ref since the nullable true/false is dependent on usage. But looks like there is a way using allOf https://github.com/swagger-api/swagger-ui/issues/4732#issuecomment-405233540 , although I've expected a different syntax. I'll fix this one

**Comment by Ladas** [comment]
@abellotti ok so I changed it to:

```
              "container_image": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/ContainerImageReference"
                  }
                ],
                "nullable": true
              },
```

And in case of more possible ref types

```
              "container_node": {
                "allOf": [
                  {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/ContainerNodeReference"
                      },
                      {
                        "$ref": "#/components/schemas/ContainerNodeReferenceByName"
                      }
                    ]
                  }
                ],
                "nullable": true
              },
```

Does that look ok to you? Btw. what validation tool do you use?

**Comment by abellotti** [comment]
Nothing fancy, I just use https://editor.swagger.io/ for a quick sanity check.

**Pull request merged**
